name: Capella CI/CD

on:
  workflow_dispatch:
    inputs:
      SERVER:
        description: "Target Server IP"
        required: true
        default: "10.0.0.4"

env:
  NUGET_PATH: "C:\\Program Files\\Nuget\\nuget.exe"
  MSBUILD_PATH: "C:\\Program Files\\Microsoft Visual Studio\\2022\\Professional\\MSBuild\\Current\\Bin\\MSBuild.exe"

jobs:

# ================= BUILD ================= #

  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore NuGet
        run: |
          echo "Nuget script..start"
          & "$env:NUGET_PATH" restore EHR-Capella5.0.sln
          echo "Nuget script..Completed"

      - name: Build Solution
        run: |
          echo "UI Building..start"
          & "$env:MSBUILD_PATH" EHR-Capella5.0.sln `
            /p:DeployOnBuild=true `
            /p:Configuration=Release `
            /p:DeleteExistingFiles=True `
            /p:Platform="Any CPU" `
            /p:PublishProfile=FolderProfile.pubxml
          echo "Building..Completed"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: capella-build
          path: EHR-Capella5.0\

# ================= DEPLOY TEST ================= #

  deploy_test_4:
    needs: build
    runs-on: windows-latest
    if: ${{ github.event.inputs.SERVER == '10.0.0.4' }}

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: capella-build

      - name: Deploy to TEST 10.0.0.4
        run: |
          echo "Backup CMG MT..Start.."
          xcopy /y /s "F:\Acurus_Web\capella_cmg_project\capella_cmg_mt\*.*" "F:\Acurus_Web\Deployee\Backup-do not delete\Git\capella_cmg_mt"
          echo "Backup Completed"

          echo "Deploy Start"
          xcopy /y /s "EHR-Capella5.0\*.*" "F:\Acurus_Web\capella_cmg_project\capella_cmg_mt\"
          echo "Deploy Completed"

# ================= DEPLOY TEST 11 ================= #

  deploy_test_11:
    needs: build
    runs-on: windows-latest
    if: ${{ github.event.inputs.SERVER == '10.0.0.11' }}

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: capella-build

      - name: Deploy to TEST 10.0.0.11
        run: |
          echo "Backup CMG MT..Start.."
          xcopy /y /s "F:\Acurus_Web\capella_cmg_project\capella_cmg_mt\*.*" "F:\Acurus_Web\Deployee\Backup-do not delete\Git\capella_cmg_mt"

          echo "Deploy Start"
          xcopy /y /s "EHR-Capella5.0\*.*" "F:\Acurus_Web\capella_cmg_project\capella_cmg_mt\"

# ================= DEPLOY PROD ================= #

  deploy_prod_6:
    needs: build
    runs-on: windows-latest
    if: ${{ github.event.inputs.SERVER == '10.1.0.6' }}

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: capella-build

      - name: Deploy PROD 10.1.0.6
        run: |
          echo "Backup Start"
          xcopy /y /s "F:\Acurus_Web\capella_cmg_project\capella_cmg_ehr\*.*" "F:\Acurus_Web\Deployee\Backup-do not delete\Git\CMG"

          echo "Deploy Start"
          xcopy /y /s "EHR-Capella5.0\*.*" "F:\Acurus_Web\capella_cmg_project\capella_cmg_ehr\"

  deploy_prod_10:
    needs: build
    runs-on: windows-latest
    if: ${{ github.event.inputs.SERVER == '10.1.0.10' }}

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: capella-build

      - name: Deploy PROD 10.1.0.10
        run: |
          xcopy /y /s "F:\Acurus_Web\capella_cmg_project\capella_cmg_ehr\*.*" "F:\Acurus_Web\Deployee\Backup-do not delete\Git\CMG"
          xcopy /y /s "EHR-Capella5.0\*.*" "F:\Acurus_Web\capella_cmg_project\capella_cmg_ehr\"

  deploy_prod_11:
    needs: build
    runs-on: windows-latest
    if: ${{ github.event.inputs.SERVER == '10.1.0.11' }}

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: capella-build

      - name: Deploy PROD 10.1.0.11
        run: |
          xcopy /y /s "F:\Acurus_Web\capella_cmg_project\capella_cmg_ehr\*.*" "F:\Acurus_Web\Deployee\Backup-do not delete\Git\CMG"
          xcopy /y /s "EHR-Capella5.0\*.*" "F:\Acurus_Web\capella_cmg_project\capella_cmg_ehr\"
