name: Capella CI/CD

on:
  workflow_dispatch:
    inputs:
      SERVER:
        description: "Target Server IP"
        required: true
        default: "10.0.0.4"

#env:
  #PUBLISH_PATH: 'D:\Acurus_Web\capella_cmg_project\capella_cmg_mt\'
env:
  NUGET_PATH: "C:\\Nuget\\nuget.exe"
  MSBUILD_PATH: "C:\\Program Files\\Microsoft Visual Studio\\2022\\Professional\\MSBuild\\Current\\Bin\\MSBuild.exe"

  
jobs:

# ================= BUILD ================= #
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install NuGet
      #- name: Setup NuGet
      #  uses: nuget/setup-nuget@v2
      - name: Restore NuGet
        shell: powershell -ExecutionPolicy Bypass {0}
        run: |          
          echo "Nuget restore start"
          & "$env:NUGET_PATH" restore "$env:GITHUB_WORKSPACE\EHR-Capella5.0.sln"
          echo "Nuget restore completed"      
      
        # Ensure publish folder exists
      - name: Ensure publish folder exists
        shell: powershell -ExecutionPolicy Bypass {0}
        run: |
         New-Item -ItemType Directory -Force -Path "$env:GITHUB_WORKSPACE\publish"
                 
      - name: Build Solution 
        shell: powershell -ExecutionPolicy Bypass {0}
        run: |
         echo "Build start"
         $msbuild = "$env:MSBUILD_PATH"
         $solution = "$env:GITHUB_WORKSPACE\EHR-Capella5.0.sln"
         $publishPath = "$env:GITHUB_WORKSPACE\publish"
         
         & $msbuild $solution `
         "/p:Configuration=Release" `
         "/p:DeployOnBuild=true" `
         "/p:PublishUrl=$publishPath" `
         "/p:PublishProfile=FolderProfile.pubxml" `
         "/p:DeleteExistingFiles=true" `
         "/p:Platform=Any CPU"
                   
          echo "Build completed"

      - name: Verify Publish Output
        shell: powershell -ExecutionPolicy Bypass {0}
        run: |
         if (Test-Path "${{ github.workspace }}\publish") {
          echo "Publish folder exists"
         dir "${{ github.workspace }}\publish"
         } else {
         echo "Publish folder NOT created"
         exit 1
         }

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: capella-build
          path: ${{ github.workspace }}\publish

     

# ================= DEPLOY TEST ================= #

  deploy_test_4:
    needs: build
    runs-on: self-hosted
    if: ${{ github.event.inputs.SERVER == '10.0.0.4' }}

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: capella-build
          path: deploy

      - name: Deploy to TEST 10.0.0.4
        shell: powershell
        run: |
          echo "Backup CMG MT..Start.."
          $sourcePath = "E:\Acurus_Web\capella_cmg_project\capella_cmg_mt"
          $backupPath = "E:\Acurus_Web\Deployee\Backup-do not delete\Git\capella_cmg_mt"
          $deployPath = "$PWD\deploy"
          Get-PSDrive -PSProvider FileSystem
          # Check if E: drive is actually available
          if (Test-Path "E:\") {
              echo "Backup CMG MT..Start.."
              
              # Ensure backup directory exists
              if (!(Test-Path $backupPath)) { 
                  New-Item -ItemType Directory -Path $backupPath -Force 
              }

              # Perform Backup
              xcopy /y /s /e /i "$sourcePath\*.*" "$backupPath\"
              echo "Backup Completed"

              echo "Deploy Start"
              #xcopy /y /s /e /i "deploy\*.*" "$sourcePath\";
              xcopy /y /s "EHR-Capella5.0\*.*" "E:\Acurus_Web\capella_cmg_project\capella_cmg_mt\"
              echo "Deploy Completed"
          }
          else {
              Write-Error "Drive D: not found. Check if the Self-Hosted runner has the drive mapped or use a different path."
              exit 1
          }
          
          #xcopy /y /s /e /i "D:\Acurus_Web\capella_cmg_project\capella_cmg_mt\*.*" "D:\Acurus_Web\Deployee\Backup-do not delete\Git\capella_cmg_mt\"
          #xcopy /y /s "F:\Acurus_Web\capella_cmg_project\capella_cmg_mt\*.*" "F:\Acurus_Web\Deployee\Backup-do not delete\Git\capella_cmg_mt"
          #echo "Backup Completed"

          #echo "Deploy Start"
          #xcopy /y /s /e /i "deploy\*.*" "D:\Acurus_Web\capella_cmg_project\capella_cmg_mt\"
          #xcopy /y /s "EHR-Capella5.0\*.*" "D:\Acurus_Web\capella_cmg_project\capella_cmg_mt\"
          #echo "Deploy Completed"

# ================= DEPLOY TEST 11 ================= #

  deploy_test_11:
    needs: build
    runs-on: windows-latest
    if: ${{ github.event.inputs.SERVER == '10.0.0.11' }}

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: capella-build

      - name: Deploy to TEST 10.0.0.11
        run: |
          echo "Backup CMG MT..Start.."
          xcopy /y /s "F:\Acurus_Web\capella_cmg_project\capella_cmg_mt\*.*" "F:\Acurus_Web\Deployee\Backup-do not delete\Git\capella_cmg_mt"

          echo "Deploy Start"
          xcopy /y /s "EHR-Capella5.0\*.*" "F:\Acurus_Web\capella_cmg_project\capella_cmg_mt\"

# ================= DEPLOY PROD ================= #

  deploy_prod_6:
    needs: build
    runs-on: windows-latest
    if: ${{ github.event.inputs.SERVER == '10.1.0.6' }}

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: capella-build

      - name: Deploy PROD 10.1.0.6
        run: |
          echo "Backup Start"
          xcopy /y /s "F:\Acurus_Web\capella_cmg_project\capella_cmg_ehr\*.*" "F:\Acurus_Web\Deployee\Backup-do not delete\Git\CMG"

          echo "Deploy Start"
          xcopy /y /s "EHR-Capella5.0\*.*" "F:\Acurus_Web\capella_cmg_project\capella_cmg_ehr\"

  deploy_prod_10:
    needs: build
    runs-on: windows-latest
    if: ${{ github.event.inputs.SERVER == '10.1.0.10' }}

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: capella-build

      - name: Deploy PROD 10.1.0.10
        run: |
          xcopy /y /s "F:\Acurus_Web\capella_cmg_project\capella_cmg_ehr\*.*" "F:\Acurus_Web\Deployee\Backup-do not delete\Git\CMG"
          xcopy /y /s "EHR-Capella5.0\*.*" "F:\Acurus_Web\capella_cmg_project\capella_cmg_ehr\"

  deploy_prod_11:
    needs: build
    runs-on: windows-latest
    if: ${{ github.event.inputs.SERVER == '10.1.0.11' }}

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: capella-build

      - name: Deploy PROD 10.1.0.11
        run: |
          xcopy /y /s "F:\Acurus_Web\capella_cmg_project\capella_cmg_ehr\*.*" "F:\Acurus_Web\Deployee\Backup-do not delete\Git\CMG"
          xcopy /y /s "EHR-Capella5.0\*.*" "F:\Acurus_Web\capella_cmg_project\capella_cmg_ehr\"
